django/django_practice/movie_info/movie_info/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path("movies/", views.movies, name="movies"),
    path("movies/<int:pk>", views.content, name="content"),
    path("movies/create/", views.create, name="create"),
    # path("movies/<int:pk>/update/", views.update, name="update"),
    # path("movies/<int:pk>/delete", views.delete, name="delete"),
]

django/django_practice/movie_info/movies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie_info.urls")),
]

django/django_practice/movie_info/movie_info/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    summary = models.TextField()
    running_time = models.IntegerField()

django/django_practice/movie_info/movie_info/forms.py
from django import forms
from .models import Movie

class InfoForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = "__all__"
        labels = {
            "title" : "제목",
            "summary" : "줄거리",
            "running_time" : "상영 시간",
        }

django/django_practice/movie_info/movie_info/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import InfoForm

# Create your views here.
def movies(request):
    inform = Movie.objects.all()
    context = {
        "titles" : inform
    }
    return render(request, "movie_info/movies.html", context)


def create(request):
    if request.method == "POST":
        form = InfoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:movies")
    else:
        form = InfoForm()
    context = {
        "form": form,
    } 
    return render(request, "movie_info/create.html", context)

def content(request, pk):
    return render(request, "movie_info/content.html")

django/django_practice/movie_info/movie_info/templates/movie_info/content.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}{% endblock %}

django/django_practice/movie_info/movie_info/templates/movie_info/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
  <h1>새 글 작성 페이지입니다.</h1>
  <div class="container">
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <footer class="d-flex justify-content-center">
        <input class="btn btn-outline-primary" type="submit" value="commit!">
      </footer>
    </form>
  </div>
{% endblock %}

django/django_practice/movie_info/movie_info/templates/movie_info/movies.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
  <h1>목록 페이지입니다.</h1>
  <a href="{% url 'movies:create' %}">
    새글 쓰러 가기
  </a>
  {% for title in titles %}
    <p class="mt-3">
      <a href="{% url 'movies:content' title.pk %}" class="text-decoration-none text-dark">
        {{ title.title }}
      </a>
    </p>
  {% endfor %}
{% endblock %}

django/django_practice/movie_info/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MovieInfo</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>
  {% block content %}{% endblock %}
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

  <body></body>

</html>