django/KDT_django/pair_PJT03/PJT03/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('reviews/', include("reviews.urls")),
]

django/KDT_django/pair_PJT03/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("", views.index, name="index"),
    path("<int:user_pk>", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("logout/", views.logout, name="logout"),
]

django/KDT_django/pair_PJT03/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("create/", views.create, name="create"),
    path("", views.index, name="index"),
    path("deatil/<int:review_pk>", views.detail, name="detail"),
    path("<int:review_pk>/update/", views.update, name="update"),
    path("<int:review_pk>/delete/", views.delete, name="delete"),
    
]

django/KDT_django/pair_PJT03/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass

django/KDT_django/pair_PJT03/reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    movie_name = models.CharField(max_length=40)
    grade = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

django/KDT_django/pair_PJT03/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm

class SignupForm(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = ("username",)
        
class UpdateForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "email",)

django/KDT_django/pair_PJT03/reviews/forms.py
from django import forms
from .models import Review

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ("title","content", "movie_name", "grade",)

django/KDT_django/pair_PJT03/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from .forms import SignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import UpdateForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')
    # 리퀘스트 메소드가 post일 땐
    # DB에 저장한다
    if request.method == "POST":
        forms = SignupForm(request.POST)
        # 유효성 검사 진행 후 DB에 저장
        if forms.is_valid():
            forms.save()
            return render(request, "base.html")
    
    # 리퀘스트 메서드가 get 또는 유효성 검사를 통과하지 못했다면,
    else:
        forms = SignupForm()
    
    context = {
        "forms" : forms,
    }
    return render(request, "accounts/signup.html", context)

def login(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')        
    # request method가 POST일 때
    if request.method == "POST":
        # 사용자의 입력값을 받는다.
        # 모델폼을 상속하는 폼이 아니기 때문에 요구하는 문법(매개변수)가 다르다.
        forms = AuthenticationForm(request, data=request.POST)
        # 유효성 검사를 통과하면 세션에 저장한다.(내장함수 login으로)
        if forms.is_valid():
            auth_login(request, forms.get_user())
            # 로그인이 요구되는 페이지를 접근하기 위해 로그인한 경우
            # 로그인이 성공하면 해당 페이지로 넘겨준다
            # 로그인 후 요청되는 페이지가 없다면 메인 페이지로 넘겨준다.
            return redirect(request.GET.get('next') or 'reviews:index')
    
    # request method가 GET 혹은 유효성 검사 실패한 사용자의 입력값이라면
    else:
        # 빈 폼 혹은 오류 메시지를 출력하는 폼
        forms = AuthenticationForm()
        
    context = {
        "forms" : forms,
    }
    return render(request, "accounts/login.html", context)

def index(request):
    # 회원 정보를 가지고 있는 유저 객체
    infos = get_user_model().objects.all()
    context = {
        "infos" : infos,
    }
    
    # 유저객체에 대한 정보를 템플릿에 출력한다.
    return render(request, "accounts/index.html", context)

# 회원 정보 조회
def detail(request, user_pk):
    # 요청으로 들어온 pk가 일치하는 유저 객체를 저장(조회하고자 하는 회원의 페이지)
    info = get_user_model().objects.get(pk=user_pk)
    context = {
        "info" : info,
    }
    return render(request, "accounts/detail.html", context)

# 회원 정보 수정
@login_required
def update(request):
    if request.method == "POST":
        forms = UpdateForm(request.POST, instance=request.user)
        if forms.is_valid():
            forms.save()
            # 수정이 완료되면 수정한 회원의 정보 보기 페이지로 보낸다.
            return redirect("accounts:detail", request.user.pk)
    else:
        forms = UpdateForm(instance=request.user)
    
    context = {
        "forms" : forms,
    }
    return render(request, "accounts/update.html", context)

def logout(request):
    auth_logout(request)
    return redirect("reviews:index")

django/KDT_django/pair_PJT03/reviews/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from .models import Review
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def create(request):
    if request.method == "POST":
        
        forms = PostForm(request.POST)
        # 사용자가 입력한 값이 유효성을 통과하면 DB에 저장한다.
        if forms.is_valid():
            forms.save()
            # 게시글 작성 후 제대로 작성됐는지 확인하도록 게시글 상세보기 페이지로 보낸다.
            pk = Review.objects.order_by("-pk")[0].pk
            return redirect("reviews:detail", pk)
        
    # request.method 가 GET일 경우
    else:
        # 빈 폼
        forms = PostForm()
    context = {
        "forms" : forms,
    }
    return render(request, "reviews/create.html", context)

def index(request):
    reviews = Review.objects.order_by("-pk")
    context = {
        "reviews" : reviews,
    }
    return render(request, "reviews/index.html", context)

def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    context = {
        "review" : review,
    }
    return render(request, "reviews/detail.html", context)

@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    # 요청이 POST로 들어온다면
    if request.method == "POST":
        forms = PostForm(request.POST, instance=review)
        if forms.is_valid():
            forms.save()
            # 수정 후 디테일 페이지로 돌아간다.
            return redirect('reviews:detail', review_pk)
    # 요청이 GET이라면
    else:
        # 사용자가 이전에 입력한 값만 있는 폼을 보여준다.
        forms = PostForm(instance=review)
    context = {
        "forms" : forms,
    }
    return render(request, "reviews/update.html", context)

@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    review.delete()
    return redirect('reviews:index')
    

django/KDT_django/pair_PJT03/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block aside %}
{% endblock %}
{% block content %}
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ info.username }}</h5>
      <h6 class="card-subtitle mb-5 text-muted">가입일 |
        {{ info.date_joined | date:"Y-n-j" }}
      </h6>
      <p class="card-text">{{ info.email }}</p>
      {% if user.pk == info.pk %}
        <a href="{% url 'accounts:update' %}" class="card-link">회원 정보 수정</a>
        {% endif %}
      </div>
  </div>
{% endblock %}

django/KDT_django/pair_PJT03/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div>
    {% for info in infos %}
      <div>
        <hr>
        <a href="{% url 'accounts:detail' info.pk %}" class="text-decoration-none">
          {{ info.username }}
        </a>
      </div>
    {% endfor %}
    <hr>
  {% endblock %}

django/KDT_django/pair_PJT03/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  <div class="w-25">
    <form action="" method="POST" class="fw-bold">
      <div class="h4 pb-2 mb-4 text-black fw-bold border-bottom border-secondary">
        로그인
      </div>
      {% csrf_token %}
      {% bootstrap_form forms %}
      <div class="text-end d-grid">
        <input type="submit" class="btn btn-outline-black" value="로그인">
      </div>
    </form>
  </div>
</div>
{% endblock %}

django/KDT_django/pair_PJT03/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="w-50 container border border-secondary rounded-3 p-5">
    <div class="h4 pb-2 mb-4 text-black fw-bold border-bottom border-secondary">
      함께 해 주세요
    </div>
    <form action="" method="POST" class="fw-bold">
      {% csrf_token %}
      {% bootstrap_form forms %}
      <div class="text-end d-grid">
        <input type="submit" class="btn btn-outline-primary" value="가입하기">
      </div>
    </form>
  </div>
{% endblock %}

django/KDT_django/pair_PJT03/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <form action="" method="POST" class="fw-bold">
    <div class="h4 pb-2 mb-4 text-black fw-bold border-bottom border-secondary">
      회원 정보 수정
    </div>
    {% csrf_token %}
    {% bootstrap_form forms %}
    <div class="text-end d-grid">
      <input type="submit" class="btn btn-outline-black" value="수정">
    </div>
  </form>

{% endblock %}

django/KDT_django/pair_PJT03/reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form forms %}
    <input type="submit" class="btn btn-primary">
  </form>
{% endblock %}
{% block aside %}{% endblock %}

django/KDT_django/pair_PJT03/reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block aside %}{% endblock %}
{% block content %}
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{{ review.title }}</h5>
      <h6 class="card-subtitle mb-5 text-muted">작성일 |
        {{ review.created_at }}
      </h6>
      <p class="card-text">{{ review.content }}</p>
      <a href="{% url 'reviews:update' review.pk %}" class="btn btn-outline-warning">수정</a>
      <a href="{% url 'reviews:delete' review.pk %}" class="btn btn-outline-danger">삭제</a>
    </div>
  </div>
{% endblock %}

django/KDT_django/pair_PJT03/reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block aside %}
  <div class="d-flex align-items-center fixed-bottom aside" style="width: 23%; padding: 2.5%; height: 20%; position: absolute; top: 20%; left:-10%;">
    <aside class="card w-100">
      <div class="card-header fw-bold">
        ÜwithMe
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item aside-list">
          <a href="{% url 'reviews:index' %}" class="nav-link">Review</a>
        </li>
        {% if user.is_authenticated %}
          <li class="list-group-item aside-list">
            <a href="{% url 'reviews:create' %}" class="nav-link">Post</a>
          </li>
        {% endif %}
      </ul>
    </aside>
  </div>
{% endblock %}
{% block content %}
  <p>
    {% for review in reviews %}
      <a href="{% url 'reviews:detail' review.pk %}" class="nav-link">
        {{ review.title }}
      </a>
    {% endfor %}
  </p>
{% endblock %}

django/KDT_django/pair_PJT03/reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form forms %}
    <input type="submit" class="btn btn-primary">
  </form>
{% endblock %}
{% block aside %}{% endblock %}

django/KDT_django/pair_PJT03/templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ReviewCommunity</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/style.css' %}">
  </head>

  <body>
    <!-- 네비게이션 바 -->
    <nav class="navbar navbar-expand-lg nav sticky-top">
      <div class="container-fluid">
        <!-- 로고 -->
        <a class="navbar-brand fw-bold" href="{% url 'reviews:index' %}" style="color:#f8f9fa;">CommÜwith
          <span style="color: #7161ef;">
            Me
          </span>
        </a>
        <!-- 반응형 웹 -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- 네브바 링크 -->
        <div class="collapse navbar-collapse" id="navbarText">
          {% block authenticated %}
          <!-- 로그인 상태에 따라 다른 화면 출력 -->
          {% if user.is_authenticated %}
          <span class="navbar-text p-0 w-100">
            <a href="{% url 'accounts:detail' user.pk %}" class="nav-link">계정 | 
              <span class="fw-bold">{{ user }}</span>
            </a>
          </span>
          <ul class="navbar-nav w-100 mb-2 mb-lg-0 fw-bold justify-content-end">          
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          </ul>
          {% else %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 fw-bold">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">Join us</a>
            </li>
          </ul>
          {% endif %}
          {% endblock %}
        </div>
      </div>
    </nav>
    <div class="container p-5 d-flex align-items-center justify-content-center position-relative" style="height: 100vh">
      <!-- 페이지에 따라 안 보이게 할 수 있도록 asdie block 지정 -->
      {% block aside %}
      <div class="d-flex align-items-center fixed-bottom aside" style="width: 23%; padding: 2.5%; height: 20%; position: absolute; top: 20%; left: -10%;">
        <aside class="card w-100">
          <div class="card-header fw-bold">
            ÜwithMe
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item aside-list">
              <a href="{% url 'reviews:index' %}" class="nav-link">Review</a>
            </li>
            {% if user.is_authenticated %}
            <li class="list-group-item aside-list">
              <a href="{% url 'reviews:create' %}" class="nav-link">Post</a>
            </li>
            {% endif %}
          </ul>
        </aside>
      </div>
      {% endblock %}
      {% block content %}
      {% endblock %}
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

</html>