django/django_practice/bootstrap_static/boards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hoguma.urls")),
]

django/django_practice/bootstrap_static/hoguma/urls.py
from django.urls import path
from . import views

app_name = "hoguma"

urlpatterns = [
    path("", views.index, name="index"),
    path("crate/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("delete/<int:pk>", views.delete, name="delete"),
]

django/django_practice/bootstrap_static/hoguma/models.py
from django.db import models

# Create your models here.
class Hoguma(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django/django_practice/bootstrap_static/hoguma/forms.py
from django import forms

# 장고에서 forms 모듈을 추가한다
from .models import Hoguma

# 모델폼에 적용될 모델을 가져온다.


class HogumaForm(forms.ModelForm):
    class Meta:
        model = Hoguma
        # 모델에서 form에 추가할 필드를 명시한다.
        fields = ["title", "content"]
        labels = {
            "title": "제목",
            "content": "내용",
        }

django/django_practice/bootstrap_static/hoguma/views.py
from django.shortcuts import render, redirect
from .models import Hoguma
from .forms import HogumaForm

# Create your views here.
def index(request):
    articles = Hoguma.objects.all()
    forms = HogumaForm()
    context = {
        "articles": articles,
        "form": forms,
    }
    return render(request, "hoguma/index.html", context)


# def create(request):
# create는 두 가지 경우로 나눌 수가 있다.
# form을 요청하는 경우(GET)와
# form에 저장하는 경우(POST)
# 하지만 모달을 사용하는 경우이므로 이 두 경우를 따로 보고,
# create에 대한 요청은 POST일 때만 요청된다고 생각한다.
def create(request):
    if request.method == "POST":
        form = HogumaForm(request.POST)
        # 폼이 유효하다면
        if form.is_valid:
            form.save()
            return redirect("hoguma:index")
        # 유효하지 않다면?
        # 모달에서 처리할 때는 유효하지 않을 때 유효성 메시지를 띄워주고
        # 아무런 페이지 처리가 일어나지 않는다.


def detail(request, pk):
    details = Hoguma.objects.get(pk=pk)
    form = HogumaForm(instance=details)
    form.fields["title"].disabled = True
    form.fields["content"].disabled = True
    context = {
        "article": details,
        "form": form,
    }
    return render(request, "hoguma/detail.html", context)


def edit(request, pk):
    content = Hoguma.objects.get(pk=pk)
    if request.method == "POST":
        form = HogumaForm(request.POST, instance=content)
        if form.is_valid():
            form.save()
            return redirect("hoguma:detail", pk)
    else:
        form = HogumaForm(instance=content)
    context = {
        "form": form,
        "article": content,
    }
    return render(request, "hoguma/edit.html", context)


def delete(request, pk):
    content = Hoguma.objects.get(pk=pk)
    content.delete()
    return redirect("hoguma:index")

django/django_practice/bootstrap_static/hoguma/templates/hoguma/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container mt-3">
    {% bootstrap_form form %}
</div>
<footer class="row">
    <div class="col text-center d-flex justify-content-center">
        <a href="{% url 'hoguma:edit' article.pk %}" class="text-end">
            <button class="btn btn-outline-primary">
                수정하기
            </button>
        </a>
        <a href="{% url 'hoguma:delete' article.pk %}" class="text-start">
            <button class="btn btn-danger">
                삭제하기
            </button>
        </a>
    </div>
</footer>
{% endblock %}

django/django_practice/bootstrap_static/hoguma/templates/hoguma/edit.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container mt-3">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <footer class="row">
            <div class="col text-center d-flex justify-content-center">
                <input type="submit" class="btn btn-outline-dark" value="저장하기">
            </div>
        </footer>
    </form>
</div>

{% endblock %}

django/django_practice/bootstrap_static/hoguma/templates/hoguma/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block content %}
<!-- 게시판 이름 -->
<header class="d-flex justify-content-center mt-3">
    <div class="ani1">
        <img src="{% static 'hoguma/images/hyemee.png' %}" alt="">
    </div>
    <h1 class="display-6 m-2 fw-bold text-center lh-base p-2">
        <span class="text-danger display-5 fw-bold">호구마</span>요?<br>호박고구마요 어머니
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#create">
            글 쓰셔야죠 어머니
        </button>
    </h1>
    <div class="ani2">
        <img src="{% static 'hoguma/images/munhee.png' %}" alt="">
    </div>
</header>


<!-- Modal -->
<div class="modal fade" id="create" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'hoguma:create' %}" method="POST">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-outline-danger" value="호구머니나">
                </form>
            </div>
        </div>
    </div>
</div>
</div>
<!-- 글 목록 -->
<table class="table table-striped w-100 mx-auto container table-hover">
    <thead>
        <tr class="row bg-dark text-white">
            <th scope="col" class="col-2">&nbsp;번호</th>
            <th scope="col" class="col text-center">제목</th>
            <th scope="col" class="col-3 text-center">작성일</th>
        </tr>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr class="row">
            <th scope="row" class="col-2 text-start">&nbsp;&nbsp;&nbsp;{{ article.pk }}</th>
            <td class="col text-start">
                <a class="text-decoration-none text-black boards" data-bs-toggle="collapse"
                    href="#collapse{{ article.pk }}" role="button" aria-expanded="false"
                    aria-controls="collapseExample">
                    {{ article.title }}
                </a>
                </p>
                <div class="collapse position-relative" id="collapse{{ article.pk }}">
                    <div class="card card-body p-3">
                        {{ article.content }}
                        <div class="position-absolute bottom-0 end-0 m-1 text-secondary" style="font-size: .5rem;">
                            {{ article.updated_at }}
                        </div>
                        <div>
                            <a href="{% url 'hoguma:edit' article.pk %}">
                                <button class="btn btn-outline-light position-absolute top-0 end-0 mx-5">
                                    <i class="bi bi-pencil-square text-muted align-top" style="font-size: .8rem"></i>
                                </button>
                            </a>
                            <a href="{% url 'hoguma:delete' article.pk %}">
                                <button class="btn btn-outline-light position-absolute top-0 end-0 mx-1 align-top"
                                    style="font-size: .8rem;">
                                    <i class="bi bi-trash3 text-muted"></i>
                                </button>
                            </a>
                        </div>
                    </div>
            </td>
            <td class="col-3">{{ article.created_at }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

django/django_practice/bootstrap_static/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'hoguma/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>

<body>
    {% block content %}
    {% endblock %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>

</body>

</html>